Updated embedded libPNG and Zlib to latest versions; Fixed bugs in find_file when compiled without libAfterBase.

diff --git a/libAfterImage/configure b/libAfterImage/configure
--- a/libAfterImage/configure
+++ b/libAfterImage/configure
@@ -885,8 +885,11 @@ Optional Packages:
   --with-xpm-includes=DIR  use libXpm includes in DIR( when builtin XPM handling is disabled )
   --with-jpeg              support JPEG image format yes
   --with-jpeg-includes=DIR use JPEG includes in DIR
+  --with-builtin-jpeg      use included JPEG  library no
   --with-png               support PNG image format yes
   --with-png-includes=DIR  use PNG includes in DIR
+  --with-builtin-png       use included PNG library no
+  --with-builtin-zlib      use included libZ library (needed for PNG) no
   --with-ungif             support Uncompressed GIF image format using libungif no
   --with-gif               support GIF image format using libgif   no
   --with-gif-includes=DIR  use GIF includes in DIR
@@ -1507,6 +1510,14 @@ else
   jpeg_includes=NO
 fi;
 
+# Check whether --with-builtin_jpeg or --without-builtin_jpeg was given.
+if test "${with_builtin_jpeg+set}" = set; then
+  withval="$with_builtin_jpeg"
+  with_builtin_jpeg="$withval"
+else
+  with_builtin_jpeg=no
+fi;
+
 # Check whether --with-png or --without-png was given.
 if test "${with_png+set}" = set; then
   withval="$with_png"
@@ -1519,6 +1530,22 @@ if test "${with_png_includes+set}" = set; then
   png_includes="$withval"
 else
   png_includes=NO
+fi;
+
+# Check whether --with-builtin_png or --without-builtin_png was given.
+if test "${with_builtin_png+set}" = set; then
+  withval="$with_builtin_png"
+  with_builtin_png="$withval"
+else
+  with_builtin_png=no
+fi;
+
+# Check whether --with-builtin_zlib or --without-builtin_zlib was given.
+if test "${with_builtin_zlib+set}" = set; then
+  withval="$with_builtin_zlib"
+  with_builtin_zlib="$withval"
+else
+  with_builtin_zlib=no
 fi;
 
 # Check whether --with-ungif or --without-ungif was given.
@@ -6673,7 +6700,11 @@ else
 	JPEG_CFLAGS="-I$jpeg_includes"
 	CPPFLAGS="$CPPFLAGS $JPEG_CFLAGS"
   fi
-  if test "${ac_cv_header_jpeglib_h+set}" = set; then
+  if test "with_builtin_jpeg" = yes -a ! -f libjpeg/jpeglib.h; then
+  	with_builtin_jpeg=no
+  fi
+  if test "$with_builtin_jpeg" = no; then
+	  if test "${ac_cv_header_jpeglib_h+set}" = set; then
   echo "$as_me:$LINENO: checking for jpeglib.h" >&5
 echo $ECHO_N "checking for jpeglib.h... $ECHO_C" >&6
 if test "${ac_cv_header_jpeglib_h+set}" = set; then
@@ -6814,6 +6845,7 @@ if test $ac_cv_header_jpeglib_h = yes; then
 fi
 
 
+  fi
   if test "$have_jpeg" = yes; then
 
 cat >>confdefs.h <<\_ACEOF
@@ -6822,8 +6854,8 @@ _ACEOF
 
 	AFTERIMAGE_LIBS="$AFTERIMAGE_LIBS -ljpeg"
   else
-	echo "$as_me:$LINENO: checking using built-in JPEG library" >&5
-echo $ECHO_N "checking using built-in JPEG library... $ECHO_C" >&6
+	echo "$as_me:$LINENO: checking built-in JPEG library" >&5
+echo $ECHO_N "checking built-in JPEG library... $ECHO_C" >&6
 	if test -f libjpeg/jpeglib.h; then
 		JPEG_OBJS='$(LIBJPEG_OBJS)'
 
@@ -7133,6 +7165,168 @@ _ACEOF
 fi
 
 
+have_png=no
+have_zlib=no
+
+if test "$with_png" = no; then
+  have_png=disabled
+else
+  SAVED_CFLAGS=$CPPFLAGS
+  if test "$png_includes" != NO; then
+	PNG_CFLAGS="-I$png_includes"
+	CPPFLAGS="$CPPFLAGS $PNG_CFLAGS"
+  fi
+  if test "$with_builtin_png" = yes -a ! -f libpng/png.h; then
+  	  with_builtin_png=no
+  fi
+  if test "$with_builtin_zlib" = yes -a ! -f zlib/zlib.h; then
+  	  with_builtin_zlib=no
+  fi
+
+  if test "$with_builtin_png" = no; then
+	  if test "${ac_cv_header_png_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for png.h" >&5
+echo $ECHO_N "checking for png.h... $ECHO_C" >&6
+if test "${ac_cv_header_png_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_png_h" >&5
+echo "${ECHO_T}$ac_cv_header_png_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking png.h usability" >&5
+echo $ECHO_N "checking png.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <png.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking png.h presence" >&5
+echo $ECHO_N "checking png.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <png.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: png.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: png.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: png.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: png.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: png.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: png.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: png.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: png.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: png.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: png.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: png.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: png.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: png.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: png.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: png.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: png.h: in the future, the compiler will take precedence" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to as-bugs@afterstep.org ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for png.h" >&5
+echo $ECHO_N "checking for png.h... $ECHO_C" >&6
+if test "${ac_cv_header_png_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_png_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_png_h" >&5
+echo "${ECHO_T}$ac_cv_header_png_h" >&6
+
+fi
+if test $ac_cv_header_png_h = yes; then
+  have_png=yes with_builtin_zlib=no
+fi
+
+
+  fi
+  if test "$with_builtin_zlib" = no; then
 
 for ac_header in zlib.h
 do
@@ -7284,157 +7478,7 @@ fi
 
 done
 
-
-if test "$with_png" = no; then
-  have_png=disabled
-else
-  SAVED_CFLAGS=$CPPFLAGS
-  if test "$png_includes" != NO; then
-	PNG_CFLAGS="-I$png_includes"
-	CPPFLAGS="$CPPFLAGS $PNG_CFLAGS"
   fi
-  have_png=no
-  if test "${ac_cv_header_png_h+set}" = set; then
-  echo "$as_me:$LINENO: checking for png.h" >&5
-echo $ECHO_N "checking for png.h... $ECHO_C" >&6
-if test "${ac_cv_header_png_h+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-fi
-echo "$as_me:$LINENO: result: $ac_cv_header_png_h" >&5
-echo "${ECHO_T}$ac_cv_header_png_h" >&6
-else
-  # Is the header compilable?
-echo "$as_me:$LINENO: checking png.h usability" >&5
-echo $ECHO_N "checking png.h usability... $ECHO_C" >&6
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-$ac_includes_default
-#include <png.h>
-_ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest.$ac_objext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_header_compiler=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-ac_header_compiler=no
-fi
-rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
-echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
-echo "${ECHO_T}$ac_header_compiler" >&6
-
-# Is the header present?
-echo "$as_me:$LINENO: checking png.h presence" >&5
-echo $ECHO_N "checking png.h presence... $ECHO_C" >&6
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include <png.h>
-_ACEOF
-if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
-  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } >/dev/null; then
-  if test -s conftest.err; then
-    ac_cpp_err=$ac_c_preproc_warn_flag
-    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
-  else
-    ac_cpp_err=
-  fi
-else
-  ac_cpp_err=yes
-fi
-if test -z "$ac_cpp_err"; then
-  ac_header_preproc=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-  ac_header_preproc=no
-fi
-rm -f conftest.err conftest.$ac_ext
-echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
-echo "${ECHO_T}$ac_header_preproc" >&6
-
-# So?  What about this header?
-case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
-  yes:no: )
-    { echo "$as_me:$LINENO: WARNING: png.h: accepted by the compiler, rejected by the preprocessor!" >&5
-echo "$as_me: WARNING: png.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
-    { echo "$as_me:$LINENO: WARNING: png.h: proceeding with the compiler's result" >&5
-echo "$as_me: WARNING: png.h: proceeding with the compiler's result" >&2;}
-    ac_header_preproc=yes
-    ;;
-  no:yes:* )
-    { echo "$as_me:$LINENO: WARNING: png.h: present but cannot be compiled" >&5
-echo "$as_me: WARNING: png.h: present but cannot be compiled" >&2;}
-    { echo "$as_me:$LINENO: WARNING: png.h:     check for missing prerequisite headers?" >&5
-echo "$as_me: WARNING: png.h:     check for missing prerequisite headers?" >&2;}
-    { echo "$as_me:$LINENO: WARNING: png.h: see the Autoconf documentation" >&5
-echo "$as_me: WARNING: png.h: see the Autoconf documentation" >&2;}
-    { echo "$as_me:$LINENO: WARNING: png.h:     section \"Present But Cannot Be Compiled\"" >&5
-echo "$as_me: WARNING: png.h:     section \"Present But Cannot Be Compiled\"" >&2;}
-    { echo "$as_me:$LINENO: WARNING: png.h: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: png.h: proceeding with the preprocessor's result" >&2;}
-    { echo "$as_me:$LINENO: WARNING: png.h: in the future, the compiler will take precedence" >&5
-echo "$as_me: WARNING: png.h: in the future, the compiler will take precedence" >&2;}
-    (
-      cat <<\_ASBOX
-## ------------------------------------ ##
-## Report this to as-bugs@afterstep.org ##
-## ------------------------------------ ##
-_ASBOX
-    ) |
-      sed "s/^/$as_me: WARNING:     /" >&2
-    ;;
-esac
-echo "$as_me:$LINENO: checking for png.h" >&5
-echo $ECHO_N "checking for png.h... $ECHO_C" >&6
-if test "${ac_cv_header_png_h+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_cv_header_png_h=$ac_header_preproc
-fi
-echo "$as_me:$LINENO: result: $ac_cv_header_png_h" >&5
-echo "${ECHO_T}$ac_cv_header_png_h" >&6
-
-fi
-if test $ac_cv_header_png_h = yes; then
-  have_png=yes
-fi
-
-
   if test "$have_png" = yes; then
         echo "$as_me:$LINENO: checking for png_get_sRGB in png.h" >&5
 echo $ECHO_N "checking for png_get_sRGB in png.h... $ECHO_C" >&6
@@ -7467,8 +7511,8 @@ _ACEOF
         AFTERIMAGE_LIBS="$AFTERIMAGE_LIBS -lpng"
         image_format="png"
   else
-	echo "$as_me:$LINENO: checking using built-in PNG libraries" >&5
-echo $ECHO_N "checking using built-in PNG libraries... $ECHO_C" >&6
+	echo "$as_me:$LINENO: checking built-in PNG library" >&5
+echo $ECHO_N "checking built-in PNG library... $ECHO_C" >&6
 	if test -f libpng/png.h; then
 		PNG_OBJS='$(LIBPNG_OBJS)'
 
@@ -7484,8 +7528,8 @@ _ACEOF
 		echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 		if test "$have_zlib" = no; then
-			echo "$as_me:$LINENO: checking using built-in ZLIB library" >&5
-echo $ECHO_N "checking using built-in ZLIB library... $ECHO_C" >&6
+			echo "$as_me:$LINENO: checking built-in ZLIB library" >&5
+echo $ECHO_N "checking built-in ZLIB library... $ECHO_C" >&6
 			if test -f zlib/zlib.h; then
 				ZLIB_OBJS='$(ZLIB_OBJS)'
 				echo "$as_me:$LINENO: result: yes" >&5
