added checks for required structures and types in elf.h for selfdiag code

diff --git a/libAfterBase/configure b/libAfterBase/configure
--- a/libAfterBase/configure
+++ b/libAfterBase/configure
@@ -5591,6 +5591,99 @@ _ACEOF
 
 
 fi
+echo "$as_me:$LINENO: checking for Elf64_Dyn.d_tag" >&5
+echo $ECHO_N "checking for Elf64_Dyn.d_tag... $ECHO_C" >&6
+if test "${ac_cv_member_Elf64_Dyn_d_tag+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <elf.h>
+
+int
+main ()
+{
+static Elf64_Dyn ac_aggr;
+if (ac_aggr.d_tag)
+return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_member_Elf64_Dyn_d_tag=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <elf.h>
+
+int
+main ()
+{
+static Elf64_Dyn ac_aggr;
+if (sizeof ac_aggr.d_tag)
+return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_member_Elf64_Dyn_d_tag=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_member_Elf64_Dyn_d_tag=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_member_Elf64_Dyn_d_tag" >&5
+echo "${ECHO_T}$ac_cv_member_Elf64_Dyn_d_tag" >&6
+if test $ac_cv_member_Elf64_Dyn_d_tag = yes; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_ELF64_DYN_D_TAG 1
+_ACEOF
+
+
+fi
 
 			echo "$as_me:$LINENO: checking for Elf64_Addr" >&5
 echo $ECHO_N "checking for Elf64_Addr... $ECHO_C" >&6
